### ISSUE TITLE
[🎯 To do] JS 연결

### ISSUE THREAD

**Issue by kwonsaebom** [FRONTENDBOOTCAMP-11th/febc11-vanilla-team7#45]
## 🔥 Issue

각 html 파일에 각 js 파일 연결하기

## ✅ TODO

- [x] main에서 script가 안불러와지는 것을 이해
- [x] main.js에서 script 태그를 만든 후에 이미 있는 파일과 연결
- [x] 페이지를 이동할 때마다 <script src="페이지.js"></script> 를 따로 main 에서 붙이는 것 (main에서는 string으로 불러와서 script 인식 못함)
