### ISSUE TITLE
[🎯 To do] 요즘 뜨는 브런치 데이터 연동

### ISSUE THREAD

**Issue by kwonsaebom** [FRONTENDBOOTCAMP-11th/febc11-vanilla-team7#47]
## 🔥 Issue

요즘 뜨는 브런치 데이터 연동하기

## ✅ TODO

- [ ] test 데이터 만들기
- [ ] 서버 연결 확인하기
- [ ] ui에 각 데이터 연결하기
